config/routes.rb
Rails.application.routes.draw do

root to: 'pages#wellcome'
devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

scope "/admin" do
  resources :users
end

resources :resources

resources :bookings

get '/wellcome' => 'pages#wellcome'
end

app/models/booking.rb
class Booking
  require 'user' 
  include Her::Model
  belongs_to :resource
  
  attributes :resource_id, :user, :start, :finish
  validates :resource_id, :presence => true
  validates :start, :presence => true
  validates :finish, :presence => true

    
  parse_root_in_json true, format: :active_model_serializers
  
  collection_path "/resources/:resource_id/bookings"
  scope :for_resource, -> (id){where(_resource_id: id) }    

    
#  custom_get :own
    
  def owner
      @owner = User.find(self.user.to_i)
  end
  
  def owner_email
      @owner = User.find(self.user.to_i).email
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  require 'resource'
  require 'db_cleaner'
    
  def index
    begin
        session[:options] ||= {}
        session[:options]['date'] ||= Date.today
        if params[:goto]
            date = Date.civil(params[:goto][:"day(1i)"].to_i,params[:goto][:"day(2i)"].to_i,params[:goto][:"day(3i)"].to_i)
            session[:options]['date'] = date
        else
            if params[:date]
                date = Date.parse(params[:date])
                session[:options]['date'] = date
            end
        end     
    

        @resources = Resource.all.collect {|r| [r.name, r.id]}
        session[:options]['resource_id'] ||= @resources.first.last.to_s

    # check if selected resource was changed by user
        if params[:resource_id]
          if @resources.detect {|name,id| id.to_s==params[:resource_id]}
            session[:options]['resource_id'] = params[:resource_id]
          end
        end 

    # initialize allowed_status
        @allowed_status = ['all', 'pending', 'approved']
        session[:options]['status'] ||= @allowed_status.first
    # check if selected status was changed by user      
        if params[:status]
          if @allowed_status.include?(params[:status])
            status = params[:status]
            session[:options]['status'] = status
          end
        end



    # put variables sent to view in sync with session[:options]      
        @resource_id = session[:options]['resource_id']
        @status = session[:options]['status']
        @date = session[:options]['date'].is_a?(String) ?  Date.parse(session[:options]['date']) : session[:options]['date']

        @resource = Resource.find(session[:options]['resource_id'])
        @all_slots = @resource.all_slots(session[:options]['date'],session[:options]['status'])
        render 'index'
    
    rescue Faraday::ClientError => e
        logger.error e.class.to_s + " - " + e.message + ' -> The API is not available'
        render 'api_not_available'
    rescue => e
        logger.error e.class.to_s + " - " + e.message     
    end
  end

 
    
  def new 
    begin
      @resource = Resource.find(params[:resource_id])
      @booking = Booking.for_resource(params[:resource_id]).create(from: params[:start], to: params[:finish], user: params[:user_id] )
      UserMailer.booking_created(@booking, @resource).deliver
      flash[:notice] = "La Reserva fue guardada exitosamente"
    rescue => e
      flash[:error] = "Booking Failed to save"
    end
      redirect_to bookings_path
  end

  def create
  end

  def edit

  end

  def update
    begin
      @resource = Resource.find(params[:resource_id])
      #byebug
      @booking = Booking.for_resource(params[:resource_id]).find(params[:id])
      remind_date = DateTime.parse(@booking.from) - 2.hours
      @booking.save   
      UserMailer.booking_approved(@booking, @resource).deliver
      #byebug
      UserMailer.delay_until(remind_date, :retry => false).booking_reminder(@booking.id, @resource.id)
      flash[:notice] = "La Reserva fue aprobada"
    rescue Redis::CannotConnectError => e
      #byebug
        logger.error e.class.to_s + " - " + e.message 
    rescue => e
      flash[:error] = "La Reserva no pudo ser aprobada"
    end
      redirect_to bookings_path
  end

  def destroy
    begin
      @resource = Resource.find(params[:resource_id])
      @booking=Booking.for_resource(@resource.id).find(params[:id])
      status=@booking.status
      # byebug
      @booking.destroy
      if status == 'pending'
        UserMailer.booking_rejected(@booking, @resource).deliver
        flash[:notice] = "La Reserva fue rechazada exitosamente"
      else
        UserMailer.booking_cancelled(@booking, @resource).deliver
        flash[:notice] = "La Reserva fue cancelada exitosamente"
      end
    rescue => e
      if status == 'pending'
        flash[:error] = "La Reserva no pudo ser rechazada"
      else 
        flash[:error] = "La Reserva no pudo ser cancelada"
      end            
    end
      redirect_to bookings_path
  end

end

app/views/bookings/_index_actions.html.erb
<% case b.status %>
              <% when 'approved' %> 
                <% if (current_user.admin? or current_user.id == b.user.to_i) %>
                  <span data-tooltip aria-haspopup="true" class="has-tip" title="Cancelar reserva"> 
                    <%= link_to "Cancelar", booking_path(resource_id: @resource_id, :id => b.id, date: @date), data: { confirm: "Are you sure?" }, :method => :delete, :class=>"fi-trash"   %>
                  </span>
                <% end %>
              <% when 'pending' %>  
                <% if current_user.admin? %>
                   <span data-tooltip aria-haspopup="true" class="has-tip" title="Aprobar reserva"> 
                    <%= link_to "Aprobar", booking_path(resource_id: @resource_id, :id => b.id, date: @date), data: { confirm: "Are you sure?" }, :method => :put, :class=>"fi-check"  %> 
                  </span>
                <% end %>
                <% if (current_user.admin? || current_user.id == b.user.to_i) %>
                  <span data-tooltip aria-haspopup="true" class="has-tip" title="Rechazar reserva"> 
                    <%= link_to "Rechazar", booking_path(resource_id: @resource_id, :id => b.id, date: @date), data: { confirm: "Are you sure?" }, :method => :delete, :class=>"fi-trash"  %>
                  </span>
                <% end %> 
              <% when 'free' %>     
               <span data-tooltip aria-haspopup="true" class="has-tip" title="Nueva reserva"> 
                  <%= link_to "Crear", new_booking_path(resource_id: @resource_id, :start => b.start, :finish => b.finish, :user_id =>current_user.id),  data: { confirm: "Are you sure?" }, :class=>"fi-pencil" %>
                </span>
              <% end %>

app/views/bookings/_index_heading.html.erb
<div class="container">
<div class="row">
   <div class="col-md-8">
       
          <h1><%=@resource.name %> -  <%= @date %></h1>
       <p>Estado:</p>
<ul class="nav nav-pills">
    <% @allowed_status.each do |s| %>
       <li role="presentation" <%= @status == s ? 'class = active' : '' %>><%= link_to s, bookings_path(status: s)%></li>    
    <% end %>
</ul>

   </div>
   <div class="col-md-4">
        <h2>Ir a</h2>
        <%= form_tag( { :action => :index }, { :method => :get }) do %>
        <%= label_tag 'new_resource_id', 'Aula:' %>
        <%= select_tag :resource_id , options_for_select(@resources, :selected => @resource_id), class: "form-control" %><br>
        <%= label_tag 'goto', 'Fecha:' %>
        <%= date_select('goto', 'day', options = {selected: @date,  include_blank: false  }, {:class => 'date-select'} )%>
        <%= submit_tag "Ir", class: "btn btn-primary" %>
        <%end%>
    </div>
  </div>
</div>

app/views/bookings/api_not_available.html.erb
<!--
To change this template use Tools | Templates.
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>API is not available</title>
</head>
<body>
The api is not available
</body>
</html>

app/views/bookings/index.html.erb
    <%= render "index_heading" %>
    <table width="100%">
      <tr>
        <th>Inicio</th>
        <th>Fin</th>
        <th>Estado </th>
        <th>Usuario </th>
        <th>Acciones </th>
      </tr>
      <%@all_slots.each do |b|%>
        <tr>
          <td>
              <%=Time.parse(b.start).strftime('%R')%>
         </td>
          <td>
              <%=Time.parse(b.finish).strftime('%R')%>
          </td>
          <td>
              <%=b.status||='free'%>
          </td>
          <td>
              <%=b.owner_email %>
          </td>
          <td>
            <%= render partial: 'index_actions', locals: {b: b, resource_id: @resource.id} %>
          </td>
        </tr>
      <%end%>
  </table>

app/views/bookings/index_own.html.erb
    <%= render "index_heading" %>
    <table width="100%">
      <tr>
        <th>Aula </th> 
        <th>Inicio</th>
        <th>Fin</th>
        <th>Estado </th>
        <th>Acciones </th>
      </tr>
      <%@own_bookings.each do |b|%>
        <tr>
          <td>
              <%=Resource.find(b.resource_id).name%>
          </td>
          <td>
              <%=Time.parse(b.start).strftime('%F %R')%>
         </td>
          <td>
              <%=Time.parse(b.finish).strftime('%F %R')%>
          </td>
          <td>
              <%=b.status%>
          </td>
          <td>
             <%= render partial: 'index_actions', locals: {b: b} %>
          </td>
        </tr>
      <%end%>
  </table>