config/routes.rb
Rails.application.routes.draw do

root to: 'pages#wellcome'
devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

scope "/admin" do
  resources :users
end

resources :resources

resources :bookings

get '/wellcome' => 'pages#wellcome'
end

app/views/layouts/_messages.html.erb
    <div class="container">
<div class="row">
  <div class="twelve columns">
    <% if flash[:error] %>
      <div class="error"><%= flash[:error] %></div>
    <% end %>

    <%if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>
  </div><!-- //.twelve.columns -->
</div><!-- //.row -->
</div><!-- //.container -->

app/views/layouts/_nav_bar.html.erb
<%= nav_bar fixed: :top, brand: "Aulas", responsive: true do %>
    <% if user_signed_in? %>
        <%= menu_group do %>
            <%= menu_item "Reservas", bookings_path(:resource_id =>'0') %>
            <%= menu_divider %>
            <% if current_user.admin? %>
                <%= drop_down "Administracion" do %>
                    <%= menu_item "Aulas", resources_path %>
                    <%= menu_item "Crear aula", new_resource_path %>
                    <%= menu_divider %>
                    <%= menu_item "Usuarios",  users_path %>
                <% end %>
            <% end %>
        <% end %>
        <%= menu_group pull: :right do %>
            <%= drop_down "Usuario: " + current_user.email do %>
                <%= menu_item "Mi cuenta", edit_user_registration_path %>
                <%= menu_item "Salir", destroy_user_session_path, :method => :delete %>
            <%end %>
        <%end %>
    <% else %>
        <%= menu_group pull: :right do %>
            <%= drop_down "Ingresar" do %>
                <%= menu_item "Registrarse", new_user_registration_path %>
                <%= menu_item "Ingresar", new_user_session_path %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Aulas-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav_bar' %>
    </header>
    <main role="main">

      <%= bootstrap_flash %>
      <%= yield %>

      </main>
  </body>
</html>